trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'Repo1'  # Your Azure DevOps project name
    pipeline: 'INTEROYAL.S3-Project--Island-'  # Your build pipeline name
    buildVersionToDownload: 'latest'  # Download the latest build artifacts
    downloadPath: '$(Pipeline.Workspace)'  # Directory to download artifacts to
    artifactName: 'INTEROYAL.S3-Project--Island-'  # The exact name of the artifact to download

- script: |
    echo "Deploying website to S3 bucket..."
    aws s3 sync $(Pipeline.Workspace)/INTEROYAL.S3-Project--Island- s3://testttting987 --delete
  displayName: 'Deploy to S3'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)  # Ensure these variables are set in your pipeline environment
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
